import Footer from "@/components/shared/footer";
import { useState } from "react";
import Modal from "@/components/shared/modal";
import RegisterInterest from "@/components/shared/register-interest";
import { useRouter } from "next/router";

const cities = [
	{
		id: "london-united-kingdom",
		name: "Fat Hippo",
		country: "@fathippofood",
		temprature: 20,
		cost: "190K followers",
		thumbUrl: "/assets/temp/309058926_665352431877687_7128083560200750965_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "lisbon-portugal",
		name: "Pit-Stop",
		country: "@pitstopff",
		temprature: 20,
		cost: "4.3K followers",
		thumbUrl: "/assets/temp/308935607_1467103023763481_3239669449011058984_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "bangkok-thailand",
		name: "Band of Burgers",
		country: "@bandofburgersuk",
		temprature: 20,
		cost: "12K followers",
		thumbUrl: "/assets/temp/309699011_802430771095374_592990536051160630_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "madeira-portugal",
		name: "Bun & Sum",
		country: "@bunandsum",
		temprature: 20,
		cost: "8K followers",
		thumbUrl: "/assets/temp/311515069_666635645111446_2700515026950178338_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "mexico-city-mexico",
		name: "Andy's Burgers",
		country: "@andysburgersuk",
		temprature: 20,
		cost: "18K followers",
		thumbUrl: "/assets/temp/313899822_141806018598311_2046522328759021892_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "berlin-germany",
		name: "Mr Wong's",
		country: "@mrwongswoknbox",
		temprature: 20,
		cost: "15K followers",
		thumbUrl: "/assets/temp/312143624_126557310190857_4310683154510412485_n.jpg",
		wifiSpeed: 28
	},
	{
		id: "paris-france",
		name: "Afrikana",
		country: "@afrikanakitchen",
		temprature: 20,
		cost: "96K followers",
		thumbUrl: "/assets/temp/img-lWhxj6p7td3hvVB1z7BSwVkU.png",
		wifiSpeed: 28
	},
	{
		id: "istanbul-turkey",
		name: "Flip & Sear",
		country: "@flipandsear",
		temprature: 20,
		cost: "3K followers",
		thumbUrl: "/assets/temp/313184957_881530653216294_2734136544431476552_n.jpg",
		wifiSpeed: 28
	}
];

const freeFeatures = [
	"Generate 50 fresh photos and content to download immediately",
	"Upload your own images to 'train' the AI",
	"Generate mobile-sized images (512x512px)"
];

const paidFeatures = [
	"Generate 1,000 unique photos and content every month",
	"Connect multiple instagram accounts",
	"Download HD versions of generated images (1024x1024)",
	"Connect your instagram for automatically branded content",
	"Themed photos for every occassion including Christmas, Easter, Eid, Halloween, New Years, Valentines and more",
	"You own all rights to images generated by the AI",
	"Use the AI to enhance your own photos",
	"Provide feedback for every image for better results every time"
];

export default function Home() {
	const [showModal, setModal] = useState(false);
	const router = useRouter();

	return (
		<div className="w-full flex flex-col bg-white dark:bg-zinc-900 dark:text-zinc-100">
			<div className="w-full flex flex-col">
				<div className="w-full max-w-4xl mx-auto py-32 px-4">
					<h1 className="text-4xl md:text-8xl font-black text-center">
						AI can make you a social-media pro
					</h1>
					<h3 className="font-poppins font-light text-2xl md:text-4xl text-center mt-5">
						Build more than a business: Build a brand.
					</h3>
					<div className="w-full flex flex-row justify-center my-2">
						<svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
							<line x1="12" y1="5" x2="12" y2="19" />
							<polyline points="19 12 12 19 5 12" />
						</svg>
					</div>

					<p className="text-xl md:text-2xl text-center text-zinc-500 font-light max-w-lg mx-auto">
						inst-AI-gram creates beautiful Instagram content without a photographer or designer
					</p>

					<div className="w-full flex flex-row justify-center mt-8 mb-2">
						<button
							className={`
								font-extrabold w-full text-xl md:text-4xl py-2 px-2 bg-black text-white dark:text-zinc-100 dark:bg-transparent 
								hover:bg-white dark:hover:bg-transparent hover:text-black group
								dark:hover:text-zinc-900 border-4 border-black dark:border-zinc-100 dark:max-w-2xl
							`}
							type="button"
							onClick={() => setModal(true)}
						>
							<div
								className={`
									w-full py-2 px-2 bg-black dark:bg-transparent group-hover:bg-white
									dark:group-hover:bg-zinc-100
								`}
							>
								Save £350+ per month &rarr;
							</div>
						</button>
						<Modal show={showModal} onClose={() => setModal(false)} size="sm">
							<RegisterInterest />
						</Modal>
					</div>
					<p className="text-center text-sm md:text-base font-semibold italic">
						Invite only — Sign up for early access!
					</p>
				</div>
			</div>

			<div className="w-full flex flex-col max-w-6xl mx-auto px-4">
				<div className="w-full flex flex-row space-x-3 items-center my-2">
					<p className="text-4xl font-black">
						Live images generated today...
					</p>
				</div>
				<div className="w-full grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
					{cities.map((city, index) => (
						<div key={city.id} className="relative group w-full aspect-square rounded-lg overflow-hidden">
							<img src={city.thumbUrl} className="absolute w-full h-full object-cover saturate-0 rounded-lg group-hover:saturate-100 group-hover:scale-105 duration-300" />
							<div className="z-10 w-full h-full flex flex-col justify-between relative group-hover:bg-black group-hover:bg-opacity-20 duration-200">
								<div className="absolute top-0 left-0 h-full w-full flex flex-col items-center justify-center text-white">
									<p
										className="font-bold text-xl md:text-2xl font-poppins group-hover:scale-125 duration-200"
										style={{ textShadow: "1px 1px 0 rgb(0 0 0 / 35%), 1px 1px 5px rgb(0 0 0 / 50%)" }}
									>
										{city.name}
									</p>
									<p
										className="font-semibold text-base font-poppins group-hover:scale-90 duration-200"
										style={{ textShadow: "1px 1px 0 rgb(0 0 0 / 35%), 1px 1px 5px rgb(0 0 0 / 50%)" }}
									>
										{city.country}
									</p>
								</div>
								<div className="absolute bottom-0 left-0 w-full flex flex-row justify-end items-center px-4 py-3 text-white text-sm md:text-base">
									<span className="">{city.cost}</span>
								</div>
							</div>
						</div>
					))}
				</div>
			</div>

			<div className="w-full mt-32">
				<div className="w-full max-w-6xl mx-auto flex flex-col space-y-20 md:flex-row md:space-y-0 md:space-x-12 items-start px-4">
					<div className="relative w-full md:w-5/12 border-4 text-black dark:text-zinc-100 border-black dark:border-zinc-100 pt-8 p-4 flex flex-col items-center">
						<p className="font-light text-xl w-full text-left tracking-wide">£14.99 one-off</p>
						<p className="font-poppins font-black text-4xl uppercase w-full text-left mb-8">
							Your social media handled
						</p>
						{freeFeatures.map((feature, index) => (
							<div className="w-full flex flex-row items-start mb-2 font-light" key={index}>
								<svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 mt-1 mr-2 shrink-0" fill="currentColor" stroke="none" viewBox="0 0 469.933 469.933">
									<path d="M429.281,44.605c-3.265-5.763-8.479-8.939-14.681-8.939c-3.482,0-6.997,1.018-9.912,2.818
											c-2.046,0.967-3.783,2.178-5.306,3.702c-92.628,92.594-171.423,169.412-254.288,242.798l-43.498-52.811
											c-4.222-5.126-8.927-6.203-12.126-6.203c-3.846,0-7.782,1.559-10.778,4.154l-0.708,0.375
											c-23.564,15.15-45.603,27.865-67.362,38.864c-5.799,2.925-9.178,7.982-9.335,13.939c-2.687,6.586-1.117,13.533,4.25,18.661
											c19.466,18.626,37.567,39.212,55.076,59.123c19.142,21.77,38.93,44.285,60.651,64.399c0.77,0.726,1.618,1.376,2.569,2.006
											c3.227,4.315,7.751,6.773,12.474,6.773c3.359,0,6.649-1.198,9.785-3.564c60.715-45.809,114.879-97.518,155.29-137.445
											c11.856-11.726,23.77-23.436,35.692-35.146c41.757-41.032,84.935-83.464,125.782-126.53c2.234-2.349,3.752-5.073,4.514-8.094
											c3.575-5.545,3.407-12.056-0.492-17.941C452.772,84.295,440.468,64.359,429.281,44.605z M429.103,114.131
											c-30.087,31.392-61.616,62.472-92.114,92.549c-16.103,15.868-32.194,31.739-48.145,47.705
											c-45.552,45.59-95.318,93.673-150.745,136.77c-18.121-17.701-35.15-37.013-51.633-55.705c-12.86-14.584-26.131-29.625-39.9-43.894
											c12.438-6.784,25.06-14.178,38.433-22.501l45.125,54.781c4.228,5.144,8.948,6.221,12.162,6.221c4.108,0,8.221-1.737,11.626-4.885
											c1.206-0.686,2.288-1.452,3.288-2.326c88.613-77.637,173.7-160.949,252.53-239.566C415.433,92.75,421.801,102.891,429.103,114.131
											z"
										/>
								</svg>
								<span className="text-xl">{feature}</span>
							</div>
						))}
					</div>
					<div className="relative w-full md:w-7/12 border-4 text-white dark:text-zinc-900 bg-black dark:bg-zinc-100 border-black dark:border-zinc-100 pt-8 p-4 flex flex-col items-center">
						<div className="absolute -top-8 right-6 border-4 text-lg border-white dark:border-zinc-900 text-white dark:text-zinc-900 py-2 px-3 uppercase bg-black dark:bg-zinc-100 font-black">
							Make your Instagram pop
						</div>
						<p className="font-light text-xl w-full text-left tracking-wide">£49.99/mo</p>
						<p className="font-poppins font-black text-4xl uppercase w-full text-left mb-8">
							Never pay for a photographer again.
						</p>
						{paidFeatures.map((feature, index) => (
							<div className="w-full flex flex-row items-start mb-2 font-light" key={index}>
								<svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 mt-1 mr-2 shrink-0" fill="currentColor" stroke="none" viewBox="0 0 469.933 469.933">
									<path d="M429.281,44.605c-3.265-5.763-8.479-8.939-14.681-8.939c-3.482,0-6.997,1.018-9.912,2.818
											c-2.046,0.967-3.783,2.178-5.306,3.702c-92.628,92.594-171.423,169.412-254.288,242.798l-43.498-52.811
											c-4.222-5.126-8.927-6.203-12.126-6.203c-3.846,0-7.782,1.559-10.778,4.154l-0.708,0.375
											c-23.564,15.15-45.603,27.865-67.362,38.864c-5.799,2.925-9.178,7.982-9.335,13.939c-2.687,6.586-1.117,13.533,4.25,18.661
											c19.466,18.626,37.567,39.212,55.076,59.123c19.142,21.77,38.93,44.285,60.651,64.399c0.77,0.726,1.618,1.376,2.569,2.006
											c3.227,4.315,7.751,6.773,12.474,6.773c3.359,0,6.649-1.198,9.785-3.564c60.715-45.809,114.879-97.518,155.29-137.445
											c11.856-11.726,23.77-23.436,35.692-35.146c41.757-41.032,84.935-83.464,125.782-126.53c2.234-2.349,3.752-5.073,4.514-8.094
											c3.575-5.545,3.407-12.056-0.492-17.941C452.772,84.295,440.468,64.359,429.281,44.605z M429.103,114.131
											c-30.087,31.392-61.616,62.472-92.114,92.549c-16.103,15.868-32.194,31.739-48.145,47.705
											c-45.552,45.59-95.318,93.673-150.745,136.77c-18.121-17.701-35.15-37.013-51.633-55.705c-12.86-14.584-26.131-29.625-39.9-43.894
											c12.438-6.784,25.06-14.178,38.433-22.501l45.125,54.781c4.228,5.144,8.948,6.221,12.162,6.221c4.108,0,8.221-1.737,11.626-4.885
											c1.206-0.686,2.288-1.452,3.288-2.326c88.613-77.637,173.7-160.949,252.53-239.566C415.433,92.75,421.801,102.891,429.103,114.131
											z"
										/>
								</svg>
								<span className="text-xl">{feature}</span>
							</div>
						))}
					</div>
				</div>
				<div className="w-full flex flex-row justify-center mt-8 px-4">
						<button
							className={`
								border-4 p-2 w-full md:w-auto border-black dark:border-zinc-100 bg-transparent focus:outline-none group
								hover:bg-black dark:hover:bg-transparent group
							`}
							type="button"
							onClick={() => router.push("/tool")}
						>
							<div
								className={`
									font-extrabold text-center w-full text-xl md:text-4xl py-2 px-3 bg-black dark:bg-transparent text-white
									dark:text-zinc-100 group-hover:bg-white dark:group-hover:bg-zinc-100 group-hover:text-black
									dark:group-hover:text-zinc-900
								`}
							>
								Your first 5 photos free &rarr;
						</div>
					</button>
				</div>
			</div>

			<div className="my-10" />

			<Footer />
		</div>
	)
}